// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CleanupBrew():Promise<main.OperationResult>;

export function GetBrewConfig():Promise<main.BrewConfig>;

export function GetInstalledPackages():Promise<Array<main.Package>>;

export function GetOutdatedPackages():Promise<Array<main.Package>>;

export function GetPackageInfo(arg1:string):Promise<string>;

export function InstallPackage(arg1:string,arg2:boolean):Promise<main.OperationResult>;

export function ReinstallPackage(arg1:string,arg2:boolean):Promise<main.OperationResult>;

export function SearchPackages(arg1:string):Promise<Array<main.Package>>;

export function SetBrewMirror(arg1:string):Promise<main.OperationResult>;

export function UninstallPackage(arg1:string,arg2:boolean):Promise<main.OperationResult>;

export function UninstallPackageWithForce(arg1:string,arg2:boolean,arg3:boolean):Promise<main.OperationResult>;

export function UpdateAllPackages():Promise<main.OperationResult>;

export function UpdateBrew():Promise<main.OperationResult>;

export function UpdatePackage(arg1:string):Promise<main.OperationResult>;
