// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CleanupBrew() {
  return window['go']['main']['App']['CleanupBrew']();
}

export function GetBrewConfig() {
  return window['go']['main']['App']['GetBrewConfig']();
}

export function GetInstalledPackages() {
  return window['go']['main']['App']['GetInstalledPackages']();
}

export function GetOutdatedPackages() {
  return window['go']['main']['App']['GetOutdatedPackages']();
}

export function GetPackageInfo(arg1) {
  return window['go']['main']['App']['GetPackageInfo'](arg1);
}

export function InstallPackage(arg1, arg2) {
  return window['go']['main']['App']['InstallPackage'](arg1, arg2);
}

export function ReinstallPackage(arg1, arg2) {
  return window['go']['main']['App']['ReinstallPackage'](arg1, arg2);
}

export function SearchPackages(arg1) {
  return window['go']['main']['App']['SearchPackages'](arg1);
}

export function SetBrewMirror(arg1) {
  return window['go']['main']['App']['SetBrewMirror'](arg1);
}

export function UninstallPackage(arg1, arg2) {
  return window['go']['main']['App']['UninstallPackage'](arg1, arg2);
}

export function UpdateAllPackages() {
  return window['go']['main']['App']['UpdateAllPackages']();
}

export function UpdateBrew() {
  return window['go']['main']['App']['UpdateBrew']();
}

export function UpdatePackage(arg1) {
  return window['go']['main']['App']['UpdatePackage'](arg1);
}
